Repository oxiton-foundation/click-metrics, pull requests merged in 2024-06, with the labels that each got.

#93 Fix sidebar
  client/src/components/navbar/sidebar.tsx
Labels: level 1, gssoc, level1

#131 GSSOC :404 not found page added with config
  client/src/App.tsx
  client/src/assets/404.png
  client/src/components/pages/NoFoundPage.tsx
  client/src/components/pages/index.ts
Labels: level 2, gssoc, level2

#137 Bug Fix: Sidebar Mobile Responsiveness
  client/src/components/navbar/header.tsx
  client/src/components/navbar/sidebar.tsx
  client/src/components/pages/home.tsx
  client/src/components/ui/search.tsx
Labels: level 2, frontend, gssoc, level2

#105 Issue in autocommenting on merged pr #88
  .github/workflows/autocomment-pr-merge.yml
Labels: level 2, gssoc, level2

#127 GSSoC: Announcement Banner for home page (Fixes #84)
  backend/.env.sample
  client/src/components/pages/home.tsx
  client/src/components/pages/homeintro.tsx
Labels: waiting for contributor

#145 Bug Fix: Update input field styling in links page
  client/src/components/pages/links.tsx
Labels: level 1, gssoc, level1

#153 Links page smalll screen style fixed
  client/src/components/pages/links.tsx
Labels: level 1, gssoc, level1

#175 Feature: fixed the search bar effect for mobile screen
  client/src/components/navbar/header.tsx
  client/src/components/ui/search.tsx
Labels: level 2, gssoc, level2

#177 Enhancement: QR Code UI update and customizations
  client/src/components/pages/qr-codes.tsx
  client/src/types/qr-code.ts
Labels: level 3, gssoc, level3
