Repository oxiton-foundation/click-metrics, pull requests merged in 2024-05, with the labels that each got.

#20 Changeing the logo
  client/index.html
  client/public/click-metrics-logo.png
  client/public/vite.svg
Labels: level 2, GSSoC

#26 Profile Dropdown
  client/src/components/navbar/header.tsx
  client/src/components/navbar/profile-dropdown.tsx
Labels: level 2, frontend, GSSoC

#27 GSSOC : Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, level 1, GSSoC

#30 Added CONTRIBUTION.md
  CONTRIBUTION.md
Labels: documentation, OOSI, level 1, GSSoC, level1

#67 Updated sidebar.tsx
  client/src/components/navbar/sidebar.tsx
Labels: OOSI, level 1, frontend, GSSoC, level1

#75 added workflow as per issue #62
  .github/workflows/autocomment-iss-close.yml
Labels: level 1, GSSoC, level1

#73 added workflows for Issue creation and PR raised
  .github/workflows/autocomment-issue.yml
  .github/workflows/autocomment-pr-raise.yml
Labels: level 2, GSSoC, level2

#74 added workflow as per issue #59
  .github/workflows/autocomment-pr-merge.yml
Labels: level 2, GSSoC, level2

#83 GSSoC: Setup Folder Structure and Basic Files for Backend using Node.js and Express #70
  backend/.env.sample
  backend/.gitignore
  backend/Readme.md
  backend/app.js
  backend/constant.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/user.controller.js
  backend/src/db/dbConnect.js
  backend/src/middlewares/auth.middleware.js
  backend/src/models/user.model.js
  backend/src/routes/user.routes.js
  backend/src/utils/ApiError.js
  backend/src/utils/ApiResponse.js
  backend/src/utils/asyncHandler.js
Labels: level 3, GSSoC, level3

#85 Sidebar has now toggle feature.
  client/src/components/navbar/sidebar.tsx
  client/src/components/pages/home.tsx
Labels: level 2, frontend, GSSoC, level2

#92 Use react hook form to validate and collect data
  client/package-lock.json
  client/package.json
  client/src/components/pages/links.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/label.tsx
  client/src/components/ui/textarea.tsx
Labels: level2
